## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - OPENEBS-SETUP
  - FUNCTIONAL
  - CHAOS
  - CLEANUP

OS-3.10-EE:
  image: openebs/openshift-ci:latest
  stage: CLUSTER-SETUP
  script:     
   - chmod 755 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/1-cluster-setup/cluster-state.sh
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/1-cluster-setup/cluster-state.sh

OPENEBS-0.8.1:
  image: openebs/openshift-ci:latest
  stage: OPENEBS-SETUP
  script:
   - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/2-setup/deploy-openebs.sh
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/2-setup/deploy-openebs.sh
  
CSTOR-POOL:
  image: openebs/openshift-ci:latest
  stage: OPENEBS-SETUP
  script:
   - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/2-setup/create-pool.sh
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/2-setup/create-pool.sh
  
APP-Deploy:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL
  parallel: 2
  script:
   - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB1-busybox-d-pvc-3-replica/busybox-3-replicas
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB1-busybox-d-pvc-3-replica/busybox-3-replicas
  
APP-load:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL
  script:
   - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB2-busybox-d-basic-load/busybox-load.sh
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB2-busybox-d-basic-load/busybox-load.sh
  
APP-snap-clone:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL
  script:
   - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB3-busybox-d-snap-clone/busybox-snap-clone.sh
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB3-busybox-d-snap-clone/busybox-snap-clone.sh
  
APP-Delete:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL
  script:
   - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB4-busybox-d-deprovision/busybox-deprovision.sh
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB4-busybox-d-deprovision/busybox-deprovision.sh
  
APP-Sts:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL
  script:
   - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB5-busybox-s-pvc-1-replica/busybox-single-replica.sh
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB5-busybox-s-pvc-1-replica/busybox-single-replica.sh
  
STS-load:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL
  script:
   - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB6-busybox-s-basic-load/busybox-load.sh
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB6-busybox-s-basic-load/busybox-load.sh
  
STS-snap-clone:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL
  script:
   - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB7-busybox-s-snap-clone/snap-clone.sh
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB7-busybox-s-snap-clone/snap-clone.sh
  
STS-Delete:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL
  script:
   - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB8-busybox-s-deprovision/deprovision.sh
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/OB8-busybox-s-deprovision/deprovision.sh
  
CSTOR-Failure:
  image: openebs/openshift-ci:latest
  stage: CHAOS
  script:
   - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/openebs-pool-failure/pool-failure.sh
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/openebs-pool-failure/pool-failure.sh
  
STORAGE-LOSS:
  image: openebs/openshift-ci:latest
  stage: CHAOS
  script:
   - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/openebs-target-container-chaos/istgt-kill.sh
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/openebs-target-container-chaos/istgt-kill.sh
  
TARGET-Loss:
  image: openebs/openshift-ci:latest
  stage: CHAOS
  script:
   - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/openebs-target-failure/target-failure.sh
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/openebs-target-failure/target-failure.sh
  
openebs-cleanup:
  image: openebs/openshift-ci:latest
  stage: CLEANUP
  script:
   - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/5-cleanup/openebs-cleanup/openebs-delete.sh
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/5-cleanup/openebs-cleanup/openebs-delete.sh
  
OS-cleanup:
  image: openebs/openshift-ci:latest
  stage: CLEANUP
  script:
   - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/5-cleanup/OS-3.10-cleanup/OS-cleanup
   - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/5-cleanup/OS-3.10-cleanup/OS-cleanup
  
